# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import themes.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='theme',
            name='photo',
            field=models.ImageField(blank=True, upload_to=themes.models.content_file_name),
        ),
    ]
