version: '3'

services:
  db:
    image: postgres
    env_file: ./.env
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

  redis:
    image: redis

  realtime:
    image: moisesdelacruz/photopublishings
    volumes:
      - ./:/webapp
    ports:
      - "3000:3000"
    depends_on:
      - redis

  web:
    build: .
    env_file: ./.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - realtime
